-- Git accounts configuration
-- Generated by git_account.lua
-- Maps to SSH hosts in /Users/hstecher/.ssh/config
return {
    ["datakaicr"] = {
        name = "datakaicr",
        email = "hstecher@datakai.net",
        ssh_host = "github.com",
    },
    ["trulieve"] = {
        name = "hstecher-trulieve",
        email = "heinz.stecher@trulieve.com",
        ssh_host = "github.com-trulieve",
    },
}